config/routes.rb
TalkingStick::Engine.routes.draw do

  get "/logout" => "devise/sessions#destroy"
  get '/delete' => 'documents#destroy'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
    resources :documents
  end
  get "rooms/:room_id/checkout" => "rooms#checkout", :as => :checkout
  post "rooms/:room_id/confirmation" => "rooms#confirmation", :as => :confirmation

  resources :documents
  resources :rooms do
    resources :documents
    resources :messages
    resources :participants do
      post 'signals', to: 'rooms#signal'
    end
  end
end

app/models/talking_stick/application_record.rb
module TalkingStick
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/talking_stick/document.rb
module TalkingStick
  class Document < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader
    belongs_to :user
    belongs_to :room
    validate :file

    def file
      if attachment.size.to_f > 2.megabytes.to_f
        error.add(:attachment, "file too heavy")
        return false
      else
        return true
      end
    end
  end
end

app/models/talking_stick/message.rb
module TalkingStick
  class Message < ApplicationRecord
    belongs_to :user, class_name: 'User'
    belongs_to :room

    validates :body, presence: true, length: {minimum: 2, maximum: 1000}

    after_create_commit { MessageBroadcastJob.perform_later(self) }

    def timestamp
      created_at.strftime('%H:%M:%S %d %B %Y')
    end
  end
end

app/models/talking_stick/participant.rb
module TalkingStick
  class Participant < ActiveRecord::Base
    belongs_to :room
    has_many :signals_sent, class_name: 'Signal', foreign_key: 'sender_id', dependent: :destroy
    has_many :signals_received, class_name: 'Signal', foreign_key: 'recipient_id', dependent: :destroy
    before_save :set_defaults

    def set_defaults
      self.joined_at ||= Time.now
      self.last_seen ||= self.joined_at
    end

    class << self
      def remove_stale!(room)
        self.where(room: room).where('last_seen < ?', Time.now - 15.seconds).destroy_all
      end
    end
  end
end

app/models/talking_stick/signal.rb
module TalkingStick
  class Signal < ActiveRecord::Base
    belongs_to :room
    belongs_to :sender, class_name: "TalkingStick::Participant"
    belongs_to :recipient, class_name: "TalkingStick::Participant"
    validates :room, :sender, :recipient, presence: true

    default_scope { order 'created_at ASC' }

    # The normal delegate method seems to not be working for an unknown reason
    def sender_guid
      self.sender.guid
    end

    def recipient_guid
      self.recipient.guid
    end
  end
end

app/controllers/talking_stick/application_controller.rb
module TalkingStick
  class ApplicationController < ActionController::Base
    layout 'application'

    #before_action :authenticate_user!
    before_action :set_locale

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end
  end
end

app/controllers/talking_stick/documents_controller.rb
require_dependency "talking_stick/application_controller"

module TalkingStick
  class DocumentsController < ApplicationController
    #before_action :set_room, only: [:index]
    #before_action :set_user, only: [:index]
    before_action :authenticate_user!
    before_action :set_document, only: [:show, :edit, :update, :destroy]

    layout 'temp_tpl'

    # GET /documents
    def index
      @documents = []
      @owner_documents = []
      @rooms = Room.where(owner_id: current_user.id).or(Room.where(user_id: current_user.id))

      @rooms.each do |room|
        @documents = @documents + room.documents.where.not(user_id: current_user.id)
        @owner_documents = @owner_documents + room.documents.where(user_id: current_user.id)
      end

    end

    # GET /documents/1
    def show
      @documents = @room.documents
    end

    # GET /documents/new
    def new
      #@room = Room.find(params[:id])
      @document = Document.new
      respond_to do |format|
        format.html { render :layout => !request.xhr? }
      end

    end

    # GET /documents/1/edit
    def edit
      @room = Room.find(params[:id]).documents
    end

    # POST /documents
    def create
      #@document = Document.new(:room_id => params[:room_id], :name => params[:name], :attachment => params[:attachment], :user_id => current_user.id)

      @document = Document.new(document_params)


      if @document.save

        respond_to :js
      end
      #format.html { redirect_to @room, notice: 'Document was successfully created.' }


    end

    # PATCH/PUT /documents/1
    def update
      if @document.update(document_params)
        redirect_to documents_path, notice: 'Document was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /documents/1
    def destroy
      @document = Document.find(params[:id])

        if @document.user_id == current_user.id
        @document.delete


        respond_to do |format|
          format.html { redirect_to documents_path }
          format.js

        end

      end
    end

    private

    def set_room
      @room = Room.find(params[:room_id])
    end

    def set_user
      @user = User.find(params[:id])
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def document_params
      params.require(:document).permit(:name, :user_id, :attachment, :room_id, :hidden)
    end
  end
end

app/controllers/talking_stick/messages_controller.rb
module TalkingStick
  class MessagesController < ApplicationController


  end
end

app/controllers/talking_stick/participants_controller.rb
require_dependency "talking_stick/application_controller"

module TalkingStick
  class ParticipantsController < ApplicationController
    before_action :set_room
    before_action :set_participant, only: [:show, :edit, :update, :destroy]

    # GET /participants
    def index
      @participants = Participant.all
    end

    # GET /participants/1
    def show
    end

    # GET /participants/new
    def new
      @participant = Participant.new
    end

    # GET /participants/1/edit
    def edit
    end

    # POST /participants
    def create
      params = participant_params.merge ip: request.remote_ip
      @participant = Participant.new(params)
      @participant.room = @room

      respond_to do |format|
        if @participant.save
          format.html { redirect_to [@room, @participant], notice: 'Participant was successfully created.' }
          format.json { render json: @participant }
        else
          render :new
        end
      end
    end

    # PATCH/PUT /participants/1
    def update
      if @participant.update(participant_params)
        redirect_to [@room, @participant], notice: 'Participant was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /participants/1
    def destroy
      @participant.destroy
      redirect_to participants_url, notice: 'Participant was successfully destroyed.'
    end

    private
      def set_room
        @room = Room.find(params[:room_id])
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_participant
        @participant = Participant.find params[:id]
      end

      # Only allow a trusted parameter "white list" through.
      def participant_params
        params.require(:participant).permit(:name, :ip, :guid)
      end
  end
end

app/controllers/talking_stick/rooms_controller.rb
require_dependency "talking_stick/application_controller"

module TalkingStick
  class RoomsController < ApplicationController
    #before_action :authenticate_user!
    before_action :set_room, only: [:show, :edit, :update, :destroy, :signal]
    before_action :set_participant, only: [:signal]

    layout 'temp_tpl'

    # GET /rooms
    def index
      @rooms = Room.all
      @users = User.all
      @reservations = Reservation.all


        # if params[:token]
      #   token = params[:token]
      #   invoice = Paydunya::Checkout::Invoice.new
      #   if invoice.confirm(token)
      #     if invoice.status == "completed"
      #       @receipt = invoice.receipt_url
      #       @this_room = invoice.get_custom_data "room"
      #       @room_payed = @rooms.find(@this_room)
      #       @room_payed.update(payed_for: true, receipt: @receipt)
      #       if @room_payed.owner.account_alias.present?
      #         direct_pay = Paydunya::DirectPay.new
      #         account_alias = @room_payed.owner.account_alias
      #         if @room_payed.cour.currency.currency_type == "€"
      #         prix_mentor = @room_payed.direct_pay_mentor
      #           if direct_pay.credit_account(account_alias, prix_mentor)
      #             @room_payed.update(payed: true)
      #           end
      #         elsif @room_payed.cour.currency.currency_type == "CFA"
      #           prix_mentor = @room_payed.p_mentor
      #           if direct_pay.credit_account(account_alias, prix_mentor)
      #             @room_payed.update(payed: true)
      #           end
      #         end
      #
      #       end
      #       redirect_to rooms_path
      #     else
      #       redirect_to rooms_path
      #     end
      #   else
      #     puts invoice.status
      #     puts invoice.response_text
      #     puts invoice.response_code
      #
      #   end
      #
      # end
    end

    def checkout

      # We will programatically simulate the last 6 cart items as checkout items
      #@items = Cart.order("created_at DESC").limit(6)
      @room = TalkingStick::Room.find(params[:room_id])


      co = Paydunya::Checkout::Invoice.new

      # co.cancel_url = "http://localhost:3000"
      # co.return_url = "http://localhost:3000"
      if @room.cour.currency.currency_type == '€'
        price = @room.unit_price_euro
        total_amount = 0.0
        #@items.each do | item |
        name = @room.name
        quantity = 1
        total_price = @room.euro_to_cfa
        co.add_item(name, quantity, price, total_price)
        co.add_custom_data("room", @room.id)
        total_amount += @room.euro_to_cfa
        #prix_uneur = @room.p_uneur

        #end
        co.total_amount += total_amount

      elsif @room.cour.currency.currency_type == 'CFA'
        price = @room.cour.price.abs.round(2)
        total_amount = 0.0
        #@items.each do | item |
        name = @room.name
        quantity = 1
        total_price = @room.p_etudiant
        co.add_item(name, quantity, price, total_price)
        co.add_custom_data("room", @room.id)
        total_amount += @room.p_etudiant
        co.total_amount += total_amount
      end

      if co.create
        redirect_to co.invoice_url
      else
        redirect_to rooms_path, :notice => co.response_text
      end

    end

    def stripe_payment
      @room = TalkingStick::Room.find(params[:room_id])

      if @room.cour.currency.currency_type == '€'
        @currency = 'eur'
      elsif @room.cour.currency.currency_type == 'CFA'
        @currency = 'xof'
      end
      @amount = @room.cour.price.abs.to_i * 100
      @distination_account = @room.owner.stripe_uid
      customer = Stripe::Customer.create(
          :email => params[:stripeEmail],
          :source => params[:stripeToken]
      )
      charge = Stripe::Charge.create({
                                         :customer => customer.id,
                                         :amount => @amount,
                                         :description => 'Paiement du cours',
                                         :currency => @currency
                                     })
      if charge.paid
        TalkingStick::Room.find(params[:room_id]).update(:payed_for => true)
        redirect_to '/rooms'
      else
        render :new
      end
    end

    # GET /rooms/1
    def show
      if (current_user.id == @room.user_id) || (current_user.id == @room.owner_id)
        @room.last_used = Time.now
        #@documents = @room.document
        #@room = Room.includes(:messages).find_or_create(slug: (params[:id] || params[:room_id]))
        @message = Message.new
        @document = Document.new
        @documents = Document.all
        @documents = @room.documents
        @reservations = Reservation.all


        @room.save

        if params[:guid]
          if @participant = Participant.where(guid: params[:guid]).first
            @participant.last_seen = Time.now
            @participant.save
          end
        end

        Participant.remove_stale! @room

        response = {
            room: @room,
            participants: @room.participants,
            signals: deliver_signals!,
        }

        respond_to do |format|
          format.html
          format.json { render json: response }
        end
      else
        redirect_to rooms_path
      end
    end

    # GET /rooms/new
    def new
      @room = Room.new
      @document = Document.new
    end

    # GET /rooms/1/edit
    def edit
    end

    # POST /rooms
    def create
      if (user_signed_in?)
        @room = Room.new(room_params)
      end
      if @room.save
        redirect_to @room, notice: 'Room was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /rooms/1
    def update
      if @room.update(room_params)
        redirect_to @room, notice: 'Room was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /rooms/1
    def destroy
      @room.destroy
      redirect_to rooms_url, notice: 'Room was successfully destroyed.'
    end

    def signal
      signal = signal_params
      signal[:room] = @room
      signal[:sender] = Participant.where(guid: signal[:sender]).first
      signal[:recipient] = @participant
      TalkingStick::Signal.create! signal
      head 204
    end

    def deliver_signals!
      data = TalkingStick::Signal.where recipient: @participant

      # Destroy the signals as we return them, since they have been delivered
      result = []
      data.each do |signal|
        result << {
            signal_type: signal.signal_type,
            sender_guid: signal.sender_guid,
            recipient_guid: signal.recipient_guid,
            data: signal.data,
            room_id: signal.room_id,
            timestamp: signal.created_at,
        }
      end
      data.delete_all
      result
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id] || params[:room_id])
    end

    def set_participant
      @participant = Participant.find(params[:participant_id])
    rescue ActiveRecord::RecordNotFound
      # Retry with ID as GUID
      @participant = Participant.where(guid: params[:participant_id]).first
      raise unless @participant
    end

    # Only allow a trusted parameter "white list" through.
    def room_params
      params.require(:room).permit(:name, :last_used, :user_id, :cour_id, :reservation_id, :availability_id,
                                   :start_day, :start_hour, :duration, :started, :done, :payed_for, :reservation_id,
                                   :owner_id, :receipt, :payed, :price, :currency)
    end

    def signal_params
      params.permit(:sender, :signal_type, :data)
    end
  end
end

app/controllers/talking_stick/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
		# You need to implement the method below in your model (e.g. app/models/user.rb)
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
		sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
		set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end

	def linkedin
		# You need to implement the method below in your model (e.g. app/models/user.rb)
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
			set_flash_message(:notice, :success, :kind => "Linkedin") if is_navigational_format?
		else
			session["devise.linkedin_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end

	def failure
		redirect_to root_path
	end

end

app/helpers/talking_stick/application_helper.rb
module TalkingStick
  module ApplicationHelper
    def gravatar_for(user, opts = {})
      opts[:alt] = user.name
      image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
                opts
    end
  end
end

app/views/talking_stick/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id%>
      <p><%= f.label :name %></p>
      <p><%= f.text_field :name, class: 'form-control' %></p>
    </div>
  </div>
  <div class="form-group">
    <div id="form-submit-buttons" class="actions">
      <p><%= f.submit "Save", class: 'btn btn-success' %>
        <span><%= link_to 'Back', rooms_path, class: 'btn btn-default pull-right' %></span>
      </p>
    </div>

  </div>
<% end %>

app/views/talking_stick/rooms/edit.html.erb
<div class="container">

  <h1>Editing Room</h1>

  <%= render 'form' %>

</div>

app/views/talking_stick/rooms/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <%= link_to t(:new_room), new_room_path, class: 'btn btn-success pull-right' %>

  <h1><%= t(:listing_rooms) %></h1>

  <table class="table">
    <thead>
      <tr>
        <th><%= t(:name) %></th>
        <th><%= t(:last_used) %></th>
        <th>Enter Room</th>
        <th>Edit Room</th>
        <th>Destroy Room</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.name %></td>
          <td><%= room.last_used.try(:strftime, "%b %d, %l:%M %P") || t(:last_used_never) %></td>
          <td><%= link_to 'Enter', room %></td>
          <td><%= link_to t(:edit), edit_room_path(room) %></td>
          <td><%= link_to t(:destroy), room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


</div>

app/views/talking_stick/rooms/new.html.erb
<div class="container"> 

  <h1>New Room</h1>

  <%= render 'form' %>

</div>

app/views/talking_stick/rooms/show.html.erb
<% content_for(:title) { "#{@room.name} Group Conversation" } %>
<div class="container-fluid" role="main" id="room" data-room-name="<%= @room.name %>">
  <div class="row">
    <div class="col-xs-3">
      <div class="row">
        <div class="col-xs-12">
          <div id="localvideo-container"></div>
        </div>
        <div class="col-xs-12">
          <span class="navbar-brand"><%= @room.name %></span>
        </div>
      </div>
    </div>
    <div class="col-xs-9">
      <div id="partnervideos"></div>
    </div>
  </div>
</div>

<div class="modal fade" role="dialog" id="video-preview">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"><%= t(:joining_room) %> "<%= @room.name %>"</h3>
      </div>
      <div class="modal-body">
        <video id="localvideo" poster="<%= image_path 'talking_stick/line-spinner.svg' %>" autoplay=true></video>
        <p id="preview_instructions"><%= t(:video_grant_access) %></p>
      </div>
      <div class="modal-footer">
        <button id="connect" type="button" class="btn btn-default btn-primary" data-dismiss="modal" disabled>Join</button>
        <%= link_to "Exit", :back, class: 'btn btn-default' %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
$(document).ready(function() {
  $('#sim').click(sim);
  // Attempt to keep the modal from scrolling vertically
  // 300px is the approximate height of the modal, minus the video
  $('#video-preview').find('video').height($(window).height() - 300);
  $('#video-preview').modal({backdrop: 'static', keyboard: false, show: true});
  var myGuid = TalkingStick.generateGUID();
  // Use the least-common-denominator, Rails API, for WebRTC setup
  var options = {
    url: '<%= room_path %>',
    myGuid: myGuid,
  };
  var signalingEngine = new TalkingStick.RailsSignaling(options);

  var options = {
    guid: myGuid,
    roomUrl: '<%= room_path %>',
    signalingEngine: signalingEngine,
    logLevel: 'trace',
  };
  TalkingStick.init(options);

  $('#connect').click(startSession);
  $(window).on('talking_stick.local_media_setup', function() {
    $('#preview_instructions').html('<%= t(:video_intro) %>');
    $('form#connect input[name="join"]').attr('disabled', false);
  });
});

function startSession() {
  $('#localvideo').detach().appendTo('#localvideo-container');
  $('#localvideo').height('auto');
  // Gotta restart and re-mute the video after moving it
  $('#localvideo')[0].play();
  TalkingStick.connect();
};

function resizeVideos() {
  var videoCollection = $('#partnervideos video');
  var numVideos = videoCollection.length;
  var square = Math.sqrt(numVideos);
  if (!isInt(square)) {
    // Round up to the next square
    square = parseInt(square) + 1;
  }
  console.log(square);
  videoCollection.css('width', (100/square) + "%");
};

function cleanupPartner() {
  resizeVideos();
}

function sim() {
  var el = $(document.createElement('video'));
  el.attr('poster', "<%= image_path 'talking_stick/line-spinner.svg' %>");
  $('#partnervideos').append(el);
  TalkingStick.localVideo = $('#localvideo');
  TalkingStick.trigger('partner.media', el);
}

function isInt(value){
  if((parseFloat(value) == parseInt(value)) && !isNaN(value)){
    return true;
  } else {
    return false;
  }
}

$(window).on('talking_stick.partner.media', resizeVideos);
$(window).on('talking_stick.partner.cleanup', cleanupPartner);
$(window).resize(resizeVideos);

</script>